### ISSUE TITLE
Handling ArchiveVo and root

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/permanent-sdk#19]
While working on #4 I have come to appreciate that my understanding of the Archive model was incorrect.

## My New Understanding

Here is what I believe is the case:

1. Archives DO NOT have children (folders nor items), although the ArchiveVo has `childFolderVOs` and `itemVOs` attributes.
2. Archives DO have a `root`, although the ArchiveVo does *not* have a `rootFolderId` attribute.

There is a `getRoot` API endpoint, but it does not accept an `archiveId`.  My understanding is this is because it relies on session data to determine which root to return.

## My Questions

1. Is the understanding above correct?
2. Is the understanding universal / true for all data? Are there legacy accounts with a different model?

## My Requests

These are both related to backend, but I'm bringing them up here for now:

3. Can we add `rootFolderId` to the ArchiveVo object?
4. Can we *also* add an optional `archiveId` parameter to the `getRoot` API.  The thinking here is that by making it optional it won't break anything that already exists / relies on session based data, but it DOES allow us to start to move away from relying on sessions to manage API parameters.

**Comment by cecilia-donnelly** [comment]
> Is the understanding above correct?
I think this is all accurate.  Thanks for writing it up.  The `getRoot` endpoint is in the folder controller, because it uses the folder `type` to get the root (as a point of interest; you probably already saw this).  The root folder for the archive has the type `type.folder.root`.  My Files, by contrast, is `type.folder.root.private`, leading into the next answer.

> Is the understanding universal / true for all data? Are there legacy accounts with a different model?
I don't know for sure.  I know that some legacy accounts have additional subroot folders.  Nowadays new archives get a My Files, a Public folder, and an Apps folder.  Some legacy accounts also have a Vault, and it looks like the default folders saw a lot of change in the first couple years of development -- look at the history of `folder.defaults.vo.php`.  I can see that nowhere in the code do we *now* set children on the archive, though, nor do we get the children anywhere (at least not using `getChildFolderVOs`).

> Can we add rootFolderId to the ArchiveVo object?
I don't see why not.  The only difficulty will be populating it in all the places where you might receive an ArchiveVO.  We can easily _find_ the root folder because it is the only one with type `type.folder.root` for each archive.

> Can we also add an optional archiveId parameter to the getRoot API.
We can easily do this!

**Comment by meisekimiu** [comment]
I personally like the second approach and agree with your reasoning: it seems the cleanest while also being close to what we eventually want without too much work. For that method do we want to hide root folders that are no longer standard, like the Vault folder?

**Comment by cecilia-donnelly** [comment]
@slifty it sounds reasonable to me! My only question is whether you'd expect that method to return *all* the root folders, including Vault for people with older accounts who have such a thing, or whether you'd explicitly limit it to our three base folders.

And @meisekimiu beat me to it!
